### ISSUE TITLE
Crashes at the start

### ISSUE THREAD

**Issue by memsql-admin** [SkidanovAlex/CtrlK#13]
1 libclang: crash detected during parsing: {
~                                               'source_filename' : '(null)'  
~                                                                             'command_line_args' : ['/usr/bin/ccache', '/home/nikita/memsql/objdir/usr/local/bin/memsql-g++', '-std=c++0x', '-I/home/nikita/memsql/objdir/usr/include', '-L/home/nikita/memsql/objdir/usr/local/lib64', '-I/usr/include', '-L/usr/local/lib64', '-DMemSqlUtil_EXPORTS', '-D_AMD64', '-D_AMD64_', '-D_AMD64', '-D_AMD64_', '-Wall', '-Werror', '-W', '-Wno-shadow', '-msse4.2', '-fcheck-new', '-lcurl', '-lpthread', '-g', '-fPIC', '-I/home/nikita/memsql', '-I/home/nikita/memsql/include', '-I/home/nikita/memsql/google-breakpad/src', '-I/home/nikita/memsql/MemSqlUtil', '-I/home/nikita/memsql/MemSqlExecute', '-I/home/nikita/memsql/parametrizer', '-I/home/nikita/memsql/snappy', '-I/home/nikita/memsql/lockfree', '-I/home/nikita/memsql/typesystem', '-o', 'CMakeFiles/MemSqlUtil.dir/execute.cpp.o', '-c', '/home/nikita/memsql/MemSqlUtil/execute.cpp', '-I/usr/lib/../lib/clang/3.2/include/'],  
~    'unsaved_files' : [],  
~                           'options' : 0,  
~                                         }

**Comment by SkidanovAlex** [comment]
Solved offline -- the problem was an old version of Clang.
